[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/users/*"
  to = "https://nodejs.dszcbaross.edu.hu:21111/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "/tervezo"
  to = "/tervezo.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200